### ISSUE TITLE
Summer Update 2024

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#297]

**Comment by muriloricci** [comment]
[Podzilla Summer Update 2024.zip](https://github.com/user-attachments/files/15571262/Podzilla.Summer.Update.2024.zip)

**Comment by mathiasbynens** [comment]
Do you still have the files with ID `33536_31744_10`? These contain the data for this part: https://tibiamaps.io/map#33790,31985,10:2

**Comment by muriloricci** [comment]
[Candia + Podzilla.zip](https://github.com/user-attachments/files/15596856/Candia.%2B.Podzilla.zip)

**Comment by mathiasbynens** [comment]
TODO list:

- [ ] The files with ID `33536_31744_10` containing the data for this part: https://tibiamaps.io/map#33790,31985,10:2
- [ ] `33280_32000_9` containing this part https://tibiamaps.io/map#33453,32171,9:2

**Comment by muriloricci** [comment]
[Podzilla Cyclopedia Floor 5.zip](https://github.com/user-attachments/files/15770218/Podzilla.Cyclopedia.Floor.5.zip)

**Comment by mathiasbynens** [comment]
> * [ ]  The files with ID `33536_31744_10` containing the data for this part: https://tibiamaps.io/map#33790,31985,10:2
> * [ ]  `33280_32000_9` containing this part https://tibiamaps.io/map#33453,32171,9:2

Addressing these two: [`improved-candia-and-podzilla.zip`](https://github.com/user-attachments/files/15774176/improved-candia-and-podzilla.zip)

**Comment by muriloricci** [comment]
> * [ ]  Explore the new Candia houses (requires help from Cip): https://www.test.tibia.com/forum/?action=thread&postid=42482#post42482

This should be addressed here: https://github.com/tibiamaps/tibia-map-data/issues/297#issuecomment-2158134175

**Comment by muriloricci** [comment]
[Upper floors - Cyclopedia.zip](https://github.com/user-attachments/files/15803109/Upper.floors.-.Cyclopedia.zip)

**Comment by mathiasbynens** [comment]
Still missing:

- `33536_32000_10` for this part https://tibiamaps.io/map#33791,32026,10:2
- `33536_32000_11` for this part https://tibiamaps.io/map#33791,32010,11:2

**Comment by mathiasbynens** [comment]
`33536_31744_11` is still missing too. https://tibiamaps.io/map#33787,31995,11:2

**Comment by muriloricci** [comment]
Isle of Merriment had some changes this Test Server.
[SU24 - Isle of Merriment.zip](https://github.com/user-attachments/files/15936367/SU24.-.Isle.of.Merriment.zip)

**Comment by mathiasbynens** [comment]
The only thing left to do related to the Summer Update is to figure out the points of interest for Candia :)

**Comment by mathiasbynens** [comment]
The maps for the very first boat task to gain access to Podzilla are missing. Around here: https://tibiamaps.io/map#33844,32002,4:1

The relevant IDs are:

- `33792_31744_4`
- `33792_32000_4`

**Comment by muriloricci** [comment]
> The only thing left to do related to the Summer Update is to figure out the points of interest for Candia :)

[Candia PoIs.zip](https://github.com/user-attachments/files/16125947/Candia.PoIs.zip) 👍

**Comment by mathiasbynens** [comment]
[`candia-north-east-house.zip`](https://github.com/user-attachments/files/16149809/candia-north-east-house.zip)

**Comment by muriloricci** [comment]
[Southeast house in Candia.zip](https://github.com/user-attachments/files/16169939/Southeast.house.in.Candia.zip)

**Comment by mathiasbynens** [comment]
Exani Hur Down in Soul Pit: [`exani-hur-down-soul-pit.zip`](https://github.com/user-attachments/files/16371064/exani-hur-down-soul-pit.zip)

**Comment by muriloricci** [comment]
I believe we can close this?
