### ISSUE TITLE
Winter Update 2017 Maps

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#45]
Hello Mathias! Here are (almost all) the maps from this update. 

This time there are new areas in the expanded map, so cropping won't be an option. These new areas are located north-east of Roshamuul, on the lower levels. 

New areas include:

- Gnome Deep Hub and new Warzones (entrance in [file `33536_32256_14`](https://tibiamaps.io/map#33536,32256,14:0)), areas east and under it. 
- Corym Mines (entrance is extension in Venore Corym Cave: [`33056_32012_11`](https://tibiamaps.io/map#33056,32012,11:0)). I'm not sure right now where the new mine is but I suspect it's just under that. There are two floors of building-like place (straight walls). 
- New Grimvale Quest dungeons:
  - Cormaya, entrance: https://tibiamaps.io/map#33353,32000,7:1
  - Edron, entrance: https://tibiamaps.io/map#33179,31923,7:1
- Some objects (Dark Stone Totems) related to the Grimvale Quest were added to existing places. Wiki mapper links here: https://tibia.wikia.com/wiki/Grimvale_Quest/Spoiler#Cormaya. I'm not 100% but I think they are on the minimap: North-east Krailos, South Banuta on water, West of Vengoth Castle's Gate

Missing maps:

- Warzone Bosses post-fight rooms (didn't get to any of them, sorry)
- Complete room of Ancient Spawn of Morgathla (You'll see two connected green/sandy rooms and there seems to be more to the east, [`33536,32256,15`](https://tibiamaps.io/map#33536,32256,15:0))
- I was told there is another Were-beast creature spawn north-west of Edron, but I didn't find it. 
- There are ~15 'Dark Stone Piles' between Cormaya and the Dark Stone Totems, but I only found ~4. I intend to get them all later and if they are on the minimap I'll open a new issue. 

I think this is it. I'm uploading my full maps to make sure I don't forget anything. Thanks for updating the map! :)

[`Minimap.WU.2017.zip`](https://github.com/tibiamaps/tibia-map-data/files/1500405/Minimap.WU.2017.zip)

**Comment by mathiasbynens** [comment]
Thanks!

Here’s that same data, converted to the format used in the repository.

[`data-winter2017.zip`](https://github.com/tibiamaps/tibia-map-data/files/1501237/data-winter2017.zip)

I’ll merge this with our data as soon as possible.

**Comment by mathiasbynens** [comment]
Entirely new files:

```
Minimap_Color_31232_32768_7.png
Minimap_Color_31232_33024_7.png
Minimap_Color_31488_30464_7.png
Minimap_Color_31488_30720_7.png
Minimap_Color_31488_30976_7.png
Minimap_Color_31488_31232_7.png
Minimap_Color_31488_31488_7.png
Minimap_Color_31488_31744_7.png
Minimap_Color_31488_32000_7.png
Minimap_Color_31488_32256_7.png
Minimap_Color_31488_32512_7.png
Minimap_Color_31488_32768_7.png
Minimap_Color_31488_33024_7.png
Minimap_Color_31744_30464_7.png
Minimap_Color_31744_30720_5.png
Minimap_Color_31744_30720_6.png
Minimap_Color_31744_30720_7.png
Minimap_Color_31744_30720_8.png
Minimap_Color_31744_31232_2.png
Minimap_Color_31744_31232_3.png
Minimap_Color_31744_31232_4.png
Minimap_Color_31744_31744_13.png
Minimap_Color_31744_31744_5.png
Minimap_Color_31744_31744_6.png
Minimap_Color_31744_32256_11.png
Minimap_Color_31744_32256_12.png
Minimap_Color_31744_33024_7.png
Minimap_Color_32000_30720_1.png
Minimap_Color_32000_30720_10.png
Minimap_Color_32000_30720_14.png
Minimap_Color_32000_30720_5.png
Minimap_Color_32000_30720_6.png
Minimap_Color_32000_30720_7.png
Minimap_Color_32000_30720_8.png
Minimap_Color_32000_31488_11.png
Minimap_Color_32000_31488_2.png
Minimap_Color_32000_32000_2.png
Minimap_Color_32000_33024_7.png
Minimap_Color_32256_30720_10.png
Minimap_Color_32256_30720_5.png
Minimap_Color_32256_30720_6.png
Minimap_Color_32256_30720_7.png
Minimap_Color_32256_30720_9.png
Minimap_Color_32256_33024_7.png
Minimap_Color_32512_30720_10.png
Minimap_Color_32512_30720_7.png
Minimap_Color_32512_30720_9.png
Minimap_Color_32512_32512_0.png
Minimap_Color_32512_32768_0.png
Minimap_Color_32512_32768_15.png
Minimap_Color_32512_33024_7.png
Minimap_Color_32768_30464_7.png
Minimap_Color_32768_30720_7.png
Minimap_Color_32768_30720_8.png
Minimap_Color_32768_30720_9.png
Minimap_Color_32768_33024_7.png
Minimap_Color_33024_30464_7.png
Minimap_Color_33024_30720_0.png
Minimap_Color_33024_30720_1.png
Minimap_Color_33024_30720_2.png
Minimap_Color_33024_30720_3.png
Minimap_Color_33024_30720_4.png
Minimap_Color_33024_30720_5.png
Minimap_Color_33024_30720_6.png
Minimap_Color_33024_30720_7.png
Minimap_Color_33024_30720_8.png
Minimap_Color_33024_30720_9.png
Minimap_Color_33024_32000_15.png
Minimap_Color_33024_32256_15.png
Minimap_Color_33024_33024_14.png
Minimap_Color_33280_30464_7.png
Minimap_Color_33280_30720_0.png
Minimap_Color_33280_30720_1.png
Minimap_Color_33280_30720_2.png
Minimap_Color_33280_30720_3.png
Minimap_Color_33280_30720_4.png
Minimap_Color_33280_30720_5.png
Minimap_Color_33280_30720_6.png
Minimap_Color_33280_30720_7.png
Minimap_Color_33280_30720_8.png
Minimap_Color_33280_30720_9.png
Minimap_Color_33280_33024_7.png
Minimap_Color_33536_30720_10.png
Minimap_Color_33536_30720_11.png
Minimap_Color_33536_30720_12.png
Minimap_Color_33536_30720_13.png
Minimap_Color_33536_30720_6.png
Minimap_Color_33536_30720_7.png
Minimap_Color_33536_30720_8.png
Minimap_Color_33536_30720_9.png
Minimap_Color_33536_30976_10.png
Minimap_Color_33536_30976_12.png
Minimap_Color_33536_32256_13.png
Minimap_Color_33536_33024_7.png
Minimap_Color_33792_30720_13.png
Minimap_Color_33792_30720_7.png
Minimap_Color_33792_30976_13.png
Minimap_Color_33792_30976_7.png
Minimap_Color_33792_31232_7.png
Minimap_Color_33792_31488_15.png
Minimap_Color_33792_31488_7.png
Minimap_Color_33792_31488_8.png
Minimap_Color_33792_31744_13.png
Minimap_Color_33792_31744_14.png
Minimap_Color_33792_31744_15.png
Minimap_Color_33792_31744_7.png
Minimap_Color_33792_31744_8.png
Minimap_Color_33792_32000_10.png
Minimap_Color_33792_32000_11.png
Minimap_Color_33792_32000_12.png
Minimap_Color_33792_32000_13.png
Minimap_Color_33792_32000_14.png
Minimap_Color_33792_32000_15.png
Minimap_Color_33792_32000_6.png
Minimap_Color_33792_32000_7.png
Minimap_Color_33792_32000_8.png
Minimap_Color_33792_32000_9.png
Minimap_Color_33792_32256_10.png
Minimap_Color_33792_32256_11.png
Minimap_Color_33792_32256_12.png
Minimap_Color_33792_32256_13.png
Minimap_Color_33792_32256_14.png
Minimap_Color_33792_32256_15.png
Minimap_Color_33792_32256_6.png
Minimap_Color_33792_32256_7.png
Minimap_Color_33792_32256_8.png
Minimap_Color_33792_32256_9.png
Minimap_Color_33792_32512_15.png
Minimap_Color_33792_32512_7.png
Minimap_Color_33792_32768_7.png
Minimap_Color_33792_33024_7.png
Minimap_Color_34048_31744_13.png
Minimap_Color_34048_31744_14.png
Minimap_Color_34048_31744_15.png
Minimap_Color_34048_32000_10.png
Minimap_Color_34048_32000_11.png
Minimap_Color_34048_32000_12.png
Minimap_Color_34048_32000_13.png
Minimap_Color_34048_32000_14.png
Minimap_Color_34048_32000_15.png
Minimap_Color_34048_32000_7.png
Minimap_Color_34048_32256_14.png
Minimap_Color_34048_32256_15.png
Minimap_Color_34048_32256_7.png
Minimap_Color_34304_31744_14.png
Minimap_Color_34304_32000_14.png
Minimap_Color_34304_32000_15.png
Minimap_Color_34304_32256_14.png
Minimap_Color_34304_32256_15.png
Minimap_WaypointCost_31232_32768_7.png
Minimap_WaypointCost_31232_33024_7.png
Minimap_WaypointCost_31488_30464_7.png
Minimap_WaypointCost_31488_30720_7.png
Minimap_WaypointCost_31488_30976_7.png
Minimap_WaypointCost_31488_31232_7.png
Minimap_WaypointCost_31488_31488_7.png
Minimap_WaypointCost_31488_31744_7.png
Minimap_WaypointCost_31488_32000_7.png
Minimap_WaypointCost_31488_32256_7.png
Minimap_WaypointCost_31488_32512_7.png
Minimap_WaypointCost_31488_32768_7.png
Minimap_WaypointCost_31488_33024_7.png
Minimap_WaypointCost_31744_30464_7.png
Minimap_WaypointCost_31744_30720_5.png
Minimap_WaypointCost_31744_30720_6.png
Minimap_WaypointCost_31744_30720_7.png
Minimap_WaypointCost_31744_30720_8.png
Minimap_WaypointCost_31744_31232_2.png
Minimap_WaypointCost_31744_31232_3.png
Minimap_WaypointCost_31744_31232_4.png
Minimap_WaypointCost_31744_31744_13.png
Minimap_WaypointCost_31744_31744_5.png
Minimap_WaypointCost_31744_31744_6.png
Minimap_WaypointCost_31744_32256_11.png
Minimap_WaypointCost_31744_32256_12.png
Minimap_WaypointCost_31744_33024_7.png
Minimap_WaypointCost_32000_30720_1.png
Minimap_WaypointCost_32000_30720_10.png
Minimap_WaypointCost_32000_30720_14.png
Minimap_WaypointCost_32000_30720_5.png
Minimap_WaypointCost_32000_30720_6.png
Minimap_WaypointCost_32000_30720_7.png
Minimap_WaypointCost_32000_30720_8.png
Minimap_WaypointCost_32000_31488_11.png
Minimap_WaypointCost_32000_31488_2.png
Minimap_WaypointCost_32000_32000_2.png
Minimap_WaypointCost_32000_33024_7.png
Minimap_WaypointCost_32256_30720_10.png
Minimap_WaypointCost_32256_30720_5.png
Minimap_WaypointCost_32256_30720_6.png
Minimap_WaypointCost_32256_30720_7.png
Minimap_WaypointCost_32256_30720_9.png
Minimap_WaypointCost_32256_33024_7.png
Minimap_WaypointCost_32512_30720_10.png
Minimap_WaypointCost_32512_30720_7.png
Minimap_WaypointCost_32512_30720_9.png
Minimap_WaypointCost_32512_32512_0.png
Minimap_WaypointCost_32512_32768_0.png
Minimap_WaypointCost_32512_32768_15.png
Minimap_WaypointCost_32512_33024_7.png
Minimap_WaypointCost_32768_30464_7.png
Minimap_WaypointCost_32768_30720_7.png
Minimap_WaypointCost_32768_30720_8.png
Minimap_WaypointCost_32768_30720_9.png
Minimap_WaypointCost_32768_33024_7.png
Minimap_WaypointCost_33024_30464_7.png
Minimap_WaypointCost_33024_30720_0.png
Minimap_WaypointCost_33024_30720_1.png
Minimap_WaypointCost_33024_30720_2.png
Minimap_WaypointCost_33024_30720_3.png
Minimap_WaypointCost_33024_30720_4.png
Minimap_WaypointCost_33024_30720_5.png
Minimap_WaypointCost_33024_30720_6.png
Minimap_WaypointCost_33024_30720_7.png
Minimap_WaypointCost_33024_30720_8.png
Minimap_WaypointCost_33024_30720_9.png
Minimap_WaypointCost_33024_32000_15.png
Minimap_WaypointCost_33024_32256_15.png
Minimap_WaypointCost_33024_33024_14.png
Minimap_WaypointCost_33280_30464_7.png
Minimap_WaypointCost_33280_30720_0.png
Minimap_WaypointCost_33280_30720_1.png
Minimap_WaypointCost_33280_30720_2.png
Minimap_WaypointCost_33280_30720_3.png
Minimap_WaypointCost_33280_30720_4.png
Minimap_WaypointCost_33280_30720_5.png
Minimap_WaypointCost_33280_30720_6.png
Minimap_WaypointCost_33280_30720_7.png
Minimap_WaypointCost_33280_30720_8.png
Minimap_WaypointCost_33280_30720_9.png
Minimap_WaypointCost_33280_33024_7.png
Minimap_WaypointCost_33536_30720_10.png
Minimap_WaypointCost_33536_30720_11.png
Minimap_WaypointCost_33536_30720_12.png
Minimap_WaypointCost_33536_30720_13.png
Minimap_WaypointCost_33536_30720_6.png
Minimap_WaypointCost_33536_30720_7.png
Minimap_WaypointCost_33536_30720_8.png
Minimap_WaypointCost_33536_30720_9.png
Minimap_WaypointCost_33536_30976_10.png
Minimap_WaypointCost_33536_30976_12.png
Minimap_WaypointCost_33536_32256_13.png
Minimap_WaypointCost_33536_33024_7.png
Minimap_WaypointCost_33792_30720_13.png
Minimap_WaypointCost_33792_30720_7.png
Minimap_WaypointCost_33792_30976_13.png
Minimap_WaypointCost_33792_30976_7.png
Minimap_WaypointCost_33792_31232_7.png
Minimap_WaypointCost_33792_31488_15.png
Minimap_WaypointCost_33792_31488_7.png
Minimap_WaypointCost_33792_31488_8.png
Minimap_WaypointCost_33792_31744_13.png
Minimap_WaypointCost_33792_31744_14.png
Minimap_WaypointCost_33792_31744_15.png
Minimap_WaypointCost_33792_31744_7.png
Minimap_WaypointCost_33792_31744_8.png
Minimap_WaypointCost_33792_32000_10.png
Minimap_WaypointCost_33792_32000_11.png
Minimap_WaypointCost_33792_32000_12.png
Minimap_WaypointCost_33792_32000_13.png
Minimap_WaypointCost_33792_32000_14.png
Minimap_WaypointCost_33792_32000_15.png
Minimap_WaypointCost_33792_32000_6.png
Minimap_WaypointCost_33792_32000_7.png
Minimap_WaypointCost_33792_32000_8.png
Minimap_WaypointCost_33792_32000_9.png
Minimap_WaypointCost_33792_32256_10.png
Minimap_WaypointCost_33792_32256_11.png
Minimap_WaypointCost_33792_32256_12.png
Minimap_WaypointCost_33792_32256_13.png
Minimap_WaypointCost_33792_32256_14.png
Minimap_WaypointCost_33792_32256_15.png
Minimap_WaypointCost_33792_32256_6.png
Minimap_WaypointCost_33792_32256_7.png
Minimap_WaypointCost_33792_32256_8.png
Minimap_WaypointCost_33792_32256_9.png
Minimap_WaypointCost_33792_32512_15.png
Minimap_WaypointCost_33792_32512_7.png
Minimap_WaypointCost_33792_32768_7.png
Minimap_WaypointCost_33792_33024_7.png
Minimap_WaypointCost_34048_31744_13.png
Minimap_WaypointCost_34048_31744_14.png
Minimap_WaypointCost_34048_31744_15.png
Minimap_WaypointCost_34048_32000_10.png
Minimap_WaypointCost_34048_32000_11.png
Minimap_WaypointCost_34048_32000_12.png
Minimap_WaypointCost_34048_32000_13.png
Minimap_WaypointCost_34048_32000_14.png
Minimap_WaypointCost_34048_32000_15.png
Minimap_WaypointCost_34048_32000_7.png
Minimap_WaypointCost_34048_32256_14.png
Minimap_WaypointCost_34048_32256_15.png
Minimap_WaypointCost_34048_32256_7.png
Minimap_WaypointCost_34304_31744_14.png
Minimap_WaypointCost_34304_32000_14.png
Minimap_WaypointCost_34304_32000_15.png
Minimap_WaypointCost_34304_32256_14.png
Minimap_WaypointCost_34304_32256_15.png
```

I’ll go ahead and add their data already.

For the rest of the maps, I’ll have to use my merge tool, so it’ll take a few days until I get to it.

**Comment by mathiasbynens** [comment]
This time there are new areas in the expanded map, so cropping won't be an option. These new areas are located north-east of Roshamuul, on the lower levels.

> These new areas are located north-east of Roshamuul, on the lower levels.

Can you be more specific? The maps expanded in every single direction again, so I’m hoping we can at least do _some_ cropping.

**Comment by LeeKunTibia** [comment]
> Can you be more specific? The maps expanded in every single direction again, so I’m hoping we can at least do _some_ cropping.

As far as I can tell, these are the map files in the expanded map. I'm a noob when it comes down to the map coordinates though, but I guess this can at least give you a direction. Also right now I can't check the minimaps in the client so it's a little bit more annoying to view the maps properly (I miss the old Tibia Map Viewer :( ).

I wonder though if it wouldn't be better to take the opportunity and start using the expanded map, which would be set for quite some time. My main concern to be honest is that Wiki's mapper code will also have to be updated for the new boundaries, and using the expanded maps right now would mean no further updates will be necessary for a few years (I guess). 

Gnome Deep Hub and Task area:
```
Minimap_Color_33536_32000_14
Minimap_Color_33536_32256_14
Minimap_Color_33792_31744_14
Minimap_Color_33792_32000_14
Minimap_Color_33792_32256_14
```
Warzones:
```
Minimap_Color_33024_32000_15
Minimap_Color_33024_32256_15
Minimap_Color_33280_32000_15
Minimap_Color_33280_32256_15
```
Boss rooms:
```
Minimap_Color_33536_32256_15
```

**Comment by mathiasbynens** [comment]
> As far as I can tell, these are the map files in the expanded map. I'm a noob when it comes down to the map coordinates though, but I guess this can at least give you a direction.

Thank you! That definitely helped. Of all the map file names you posted, only these three are outside of the current map’s bounds:

* [`Minimap_Color_33792_31744_14`](https://tibiamaps.io/map#33792,31744,14:0)
* [`Minimap_Color_33792_32000_14`](https://tibiamaps.io/map#33792,32000,14:0)
* [`Minimap_Color_33792_32256_14`](https://tibiamaps.io/map#33792,32256,14:0)

That’s good news because it means we don’t have to expand by too much.

> I wonder though if it wouldn't be better to take the opportunity and start using the expanded map, which would be set for quite some time. My main concern to be honest is that Wiki's mapper code will also have to be updated for the new boundaries, and using the expanded maps right now would mean no further updates will be necessary for a few years (I guess). 

Increasing the bounds of our map data slows down the script that generates the various map formats. That’s why I prefer to expand the bounds when absolutely necessary.

**Comment by LeeKunTibia** [comment]
I'm glad we're (almost) done with this one! I found a problem though in an area that was previously "explored", but it was actually just manually painted gray:

https://tibiamaps.io/map#33413,32054,9:1

It's just one file [33280_32000_9], if you merge this one with yours giving mine the priority over explored areas (or simply replace it and let go of the big gray square) it should be fixed. 

Thanks for your work on this. :)

**Comment by LeeKunTibia** [comment]
I just found and mapped a new area, it's under the Gnome Hub and it's part of the Opticording Spheres Quest. Just one file was changed. 
![minimap_color_33792_32000_15](https://user-images.githubusercontent.com/31053487/33745392-c904dd92-db9d-11e7-82a7-7d56d513effb.png)
![minimap_waypointcost_33792_32000_15](https://user-images.githubusercontent.com/31053487/33745409-d720797c-db9d-11e7-8f1e-61f18b7b4592.png)

**Comment by mathiasbynens** [comment]
> I found a problem though in an area that was previously "explored", but it was actually just manually painted gray:
>
> https://tibiamaps.io/map#33413,32054,9:1

Thanks! Fixing now… Just for the record, this wasn’t manually painted, it was imported as part of #40. So, according to TibiaCast data, there was grey rock there at one point!

**Comment by mathiasbynens** [comment]
@LeeKunTibia Could you please ZIP and upload the `33792_3200_15` files? If not, I can try to work off of the compressed PNG, but that would be more annoying :)

**Comment by mathiasbynens** [comment]
Never mind, I got it working :) Thanks!

**Comment by mathiasbynens** [comment]
> I just found and mapped a new area, it's under the Gnome Hub and it's part of the Opticording Spheres Quest. Just one file was changed 33792_32000_15.

Fixed in 5da2634e30a400dd225bc28c2094be3d65e36c3b!

**Comment by LeeKunTibia** [comment]
And I've got more... Hopefully this is the one before last (Spawn of Morgathla area still missing). It's the Headquarter of the Planegazers, the boss lever room and the bosses fight room. Only one file but two floors, here: https://tibiamaps.io/map#33911,32103,15:0 and above. 

[Minimap Last Planegazer.zip](https://github.com/tibiamaps/tibia-map-data/files/1577670/Minimap.Last.Planegazer.zip)

**Comment by mathiasbynens** [comment]
> And I've got more... Hopefully this is the one before last (Spawn of Morgathla area still missing). It's the Headquarter of the Planegazers, the boss lever room and the bosses fight room. Only one file but two floors, here: https://tibiamaps.io/map#33911,32103,15:0 and above.

Added in 48f5eaf37bc1c5f09e3b3852a83ad4e605216f11. Thanks!

**Comment by LeeKunTibia** [comment]
This is it... Almost. I got the maps from the Lava Pumps (after warzone bosses), and all Ancient Spawn of Morgathla rooms from another player ([Slayer Saver](https://secure.tibia.com/community/?subtopic=characters&name=Slayer%20Saver)). The maps aren't fully explored, but I'm not sure when/if ever I'll go there myself, so it's a good start. Also, they have some parts less-explored than what we currently have, so it requires a merge instead of replacement. 

[Dangerous Depths Final Rooms.zip](https://github.com/tibiamaps/tibia-map-data/files/1590276/Dangerous.Depths.Final.Rooms.zip)

General update as far as I can tell:

- Missing full exploration of Ancient Spawn of Morgathla rooms
- Missing update existing maps where [Dark Stone Piles](http://tibia.wikia.com/wiki/Dark_Stone_Pile) were added (they are represented as a white pixel). I do have these maps already, but I must select the files and send them. Locations can be found [here](http://tibia.wikia.com/wiki/Ley_Line) if anyone wants to go get them. :P
- If you look closely, there seems to be more to the north-east of the Morgathla rooms I just sent. I have no idea if that really exists since theoretically the quest has been fully spoiled.

**Comment by LeeKunTibia** [comment]
Here are the files for the Dark Stone Piles and Dark Stone Totems. The +1 Floor file at Vengoth correspond to the Dark Stone Totem there. Some of these (Vengoth, Cormaya west) are on the exact edge pixel of the file, by the way. Stone Piles are a white pixel, and the totems (Also on Krailos and Banuta) are black. 

[Dark Stone Piles.zip](https://github.com/tibiamaps/tibia-map-data/files/1599140/Dark.Stone.Piles.zip)

**Comment by mathiasbynens** [comment]
@LeeKunTibia Addressed your last two comments in 40e8aad6c00e3b06c51b27dcd9a4e1e6373fc045 and ad2842822cf9ca89151e2af4671cf60325e521ec, respectively. Thanks!

**Comment by hadewych** [comment]
Can anyone update it to me? Where to download and paste last update?

**Comment by mathiasbynens** [comment]
@hadewych https://tibiamaps.io/downloads. I’m removing your comment now as it’s off-topic.
